### ISSUE TITLE
Support tarball creation

### ISSUE THREAD

**Issue by l0kod** [alexcrichton/git2-rs#174]
It would be useful to be able to create a `tar::Builder` from a `git2::Tree` object.

This should also be useful for Cargo to create deterministic archives/packages.

**Comment by alexcrichton** [comment]
Seems like a nifty idea! Perhaps a separate crate, though?

**Comment by alexcrichton** [comment]
I'm going to close this for now as I think this should be in a separate crate.

**Comment by dekellum** [comment]
May I ask the original requester, @l0kod : was this a suggestion to support a library feature equivalent of `git archive` via this crate?  If so I think that would be useful, but note that there is no `archive` high level API in the underlying libgit2 (that I could find).  

@alexcrichton would that detail of the feature (e.g. tarball of file content from local repo instead of working tree copy, which could be dirty) change your stated position that this is better separated? I'm just looking for clarification here.

**Comment by alexcrichton** [comment]
I believe this would still be best done as a separate crate, not built directly into the `git2` crate.
