### ISSUE TITLE
Adding git2-rs as dependency triggers dynamic linking error

### ISSUE THREAD

**Issue by casey** [alexcrichton/git2-rs#175]
Adding git2 as a dependency in my project's Cargo.toml causes cargo run to report a linker error:

```
$ cargo run
   Compiling x v0.0.0 (file:///Users/rodarmor/src/x)
    Finished debug [unoptimized + debuginfo] target(s) in 3.8 secs
     Running `target/debug/x`
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /opt/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

I created a repo which contains a hopefully minimal reproduction: [casey/git2-glium-dynamic-link-error](https://github.com/casey/git2-glium-dynamic-link-error)

Usually these kinds of errors are caused by bad values in the environment variables `DYLD_LIBRARY_PATH` and pals, but I checked my env and I don't see anything suspicious.

I theorize that something wacky is happening with git2 and cmake. Perhaps pkg-config thinks that it should load things from `/opt/local/lib`?

**Comment by alexcrichton** [comment]
Hm I feel like I've heard of this before... Could you do a full clean and then gist the output of `cargo build -vv`?

**Comment by casey** [comment]
Yup yup, here it is: https://gist.github.com/casey/7d4d6d35954ec49896fd2bae304f57bd

**Comment by alexcrichton** [comment]
Ah ok I think I see what's happening. It looks like OpenSSL is getting [picked up in `/opt/local/lib`](https://gist.github.com/casey/7d4d6d35954ec49896fd2bae304f57bd#file-cargo-build-vv-output-L82-L84). I've seen this sort of error before where `libJPEG.dylib` (I think part of some jpeg library) conflicts with the library that *should* be loaded because the load paths are misconfigured.

I'm not 100% sure where the dependency on `ImageIO` comes from but my guess [is `OpenGL`](https://gist.github.com/casey/7d4d6d35954ec49896fd2bae304f57bd#file-cargo-build-vv-output-L1072).

The "fix" here would be to drop the OpenSSL dependency, which I believe is coming from libssh2 which libgit2 depends on. Do you need ssh urls enabled? If no, perhaps the `ssh` feature of this crate could be disabled?

**Comment by casey** [comment]
Yup, I can definitely do that, it does fix the immediate problem.

Thinking about the underlying issue though, do you know why the load paths are getting misconfigured?

CMake is finding openssl in /opt/local/lib, which is fine, but then the OS X frameworks are looking for the dylibs they need in /opt/local/lib, and not falling back to the resources that they're bundled with, which confuses me.

**Comment by casey** [comment]
I whittled it down further: https://github.com/casey/rust-dynamic-linker-error

I'm going to experiment with modifying `openssl-sys`'s build script, so I can figure out exactly what the issue is.

I'll close this issue, since it's clearly not git2-rs specific.

I'll open an issue on openssl-sys (or core-graphics, if that's where the problem is), hopefully with a fix!
