### ISSUE TITLE
libgit2-sys provides no way to use a system provided libgit2

### ISSUE THREAD

**Issue by jmesmon** [alexcrichton/git2-rs#68]

**Comment by alexcrichton** [comment]
The libgit2-sys library specifies [the `links` manifest key](https://github.com/alexcrichton/git2-rs/blob/master/libgit2-sys/Cargo.toml#L6) which [allows overrides](http://doc.crates.io/build-script.html#overriding-build-scripts), but the system library is almost never the right version so that's why the check isn't currently implemented.

**Comment by jmesmon** [comment]
I still think this is an issue, perhaps more accurately stated as:
```
libgit2-sys provides no way to use a system provided libgit2 via pkg-config
```

Notably, this means that pkg-config would need to be driven by an external program and it's output translated into something like the overrides for links (only to be converted later by cargo back into the original form). That seems rather awkward and unnecessary.

**Comment by alexcrichton** [comment]
Right, this was explicitly removed in b5334b057b555d77aed4a0031c7b83b4186aa4f7 because the depended-upon version of libgit2 is rarely found in the wild, and future versions of libgit2 frequently break ABI compatibility, so it really does need to use a precise version for now until the ABI stabilizes.

**Comment by jmesmon** [comment]
I opened this because right now I am packaging a recent enough libgit2, and have to add this nasty patch to git2-rs to get it to be used: https://github.com/jmesmon/meta-rust/blob/master/recipes/cargo/files/git2-rs/0002-libgit2-sys-avoid-the-build-script-it-is-a-disaster.patch

I'd expect it might be a good idea to at least allow some type of override to get the expected pkg-config behavior so packagers can hack up packages a bit less.

**Comment by alexcrichton** [comment]
Hm ok, how about something like if the `LIBGIT2_SYS_USE_PKG_CONFIG` environment variable is set, then `pkg-config` is queried first, but otherwise it's not used at all. Would that work?

**Comment by jmesmon** [comment]
That would be fine.

**Comment by alexcrichton** [comment]
Ok! I've added this in https://github.com/alexcrichton/git2-rs/commit/ed629d783f629838611f07c5940a2608b7f97959
